CREATE TABLE t_category(
	 _ID INTEGER 	PRIMARY KEY AUTOINCREMENT,
	 CATEGORY_NAME	TEXT 	NOT NULL,
	 CATEGORY_TYPE	INTEGER AUTOINCREMENT,
	 CATEGORY_ORDER	INTEGER DEFAULT 0,
	 CATEGORY_ICON	TEXT
);
CREATE TABLE t_app(
	 _ID INTEGER PRIMARY KEY AUTOINCREMENT,
	 APP_NAME		TEXT 	NOT NULL,
	 APP_PACKAGE	TEXT 	NOT NULL,
	 CATEGORY_ID	INTEGER NOT NULL,
	 APP_ICON		INTEGER,
	 APP_ORDER		INTEGER DEFAULT 0,
	 APP_FLG		INTEGER DEFAULT 0,
	 START_TIMES	INTEGER DEFAULT 0,
);

INSERT INTO t_category (_ID,CATEGORY_NAME,CATEGORY_TYPE,CATEGORY_ORDER,CATEGORY_ICON) VALUES(1,"系统软件",1,1,NULL);
INSERT INTO t_category (_ID,CATEGORY_NAME,CATEGORY_TYPE,CATEGORY_ORDER,CATEGORY_ICON) VALUES(2,"游戏",2,2,NULL);
INSERT INTO t_category (_ID,CATEGORY_NAME,CATEGORY_TYPE,CATEGORY_ORDER,CATEGORY_ICON) VALUES(3,"未分类",3,3,NULL);